# -*- coding: utf-8 -*-
"""dat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sZid5RhRN8O2p00Kya_Sl9AbKjV11Io
"""

# Cell 1: Install git (already in Colab) + setup your info
!git config --global user.email "glo.wan.kih@gmail.com"   # ← CHANGE THIS
!git config --global user.name "Kaaybe"              # ← CHANGE THIS

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# 
# st.set_page_config(page_title="AI Data Analyzer", layout="wide")
# st.title("AI Data Analyzer")
# st.caption("Upload CSV → get stats + beautiful histogram")
# 
# file = st.file_uploader("Upload CSV or JSON", type=["csv","json"])
# 
# if file:
#     df = pd.read_csv(file) if file.name.endswith('.csv') else pd.read_json(file)
# 
#     # Clean data
#     for c in df.columns:
#         if df[c].dtype == 'float64' or df[c].dtype == 'int64':
#             df[c].fillna(df[c].mean(), inplace=True)
#         else:
#             df[c].fillna("Unknown", inplace=True)
# 
#     col1, col2 = st.columns(2)
#     with col1: st.write("Preview"); st.dataframe(df.head(10))
#     with col2: st.write(f"Shape: {df.shape}"); st.write(df.dtypes)
# 
#     st.write("### Statistics"); st.dataframe(df.describe(include='all'))
# 
#     nums)
# 
#     nums = df.select_dtypes(include=np.number).columns
#     if len(nums)>0:
#         col = st.selectbox("Histogram column", nums)
#         fig, ax = plt.subplots(figsize=(8,5))
#         df[col].hist(bins=30, ax=ax, color="#4ECDC4", edgecolor="black")
#         ax.set_title(f"Distribution of {col}")
#         st.pyplot(fig)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# scikit-learn

!git remote add origin https://github.com/Kaaybe/ai_data_analyzer